#######################################################
#       PROJECT Makefile
#
# This is what the programs makefile would look like
# These are the only variables you will need to define
######################################################

APP            = noptc 
C_SRC          = noptc.c #hello.c
#CPP_SRC        = myapp.cpp  base_classes.cpp
INSTALL_DIR    = /usr/local/lib/nopoll-test/
CFLAGS	       +=-I/usr/local/include/nopoll
LINK		+=-L/usr/local/lib -lnopoll

# And include the template Makefile, make sure its
# path is correct.  
 
.include "../../mk/bsd_make.mk"
